import { BookOpen, Tractor, Sprout, Droplets, Bug, Sun, Coins } from "lucide-react";

export interface Step {
  icon: any;
  title: string;
  detail: string;
}

export interface TraditionalMethod {
  title: string;
  img: string;
  text: string;
}

export interface PlantingCrop {
  id: string;
  name: string;
  emoji: string;
  season: string;
  duration: string;
  yield: string;
  hero: string;
  description: string;
  steps: Step[];
  traditional: TraditionalMethod[];
  videoId: string;
}

export const PLANTING_GUIDE_DATA: Record<string, PlantingCrop[]> = {
  en: [
    {
      id: "wheat",
      name: "Wheat (गेहूँ)",
      emoji: "🌾",
      season: "Rabi (Oct–Apr)",
      duration: "120–150 days",
      yield: "18–22 qtl/acre",
      hero: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=1200&q=80",
      description: "Wheat is India's most important Rabi cereal. With good seed, timely sowing and 4–5 irrigations, you can harvest a healthy crop in about 4 months.",
      videoId: "PD3Z9q1eYjE",
      steps: [
        { icon: BookOpen, title: "1. Choose seed variety", detail: "Pick a certified variety suited to your region — HD-2967, PBW-550 or DBW-187. Buy 40 kg seed per acre from KVK or licensed dealer." },
        { icon: Tractor, title: "2. Prepare the land", detail: "Plough 2–3 times to a fine tilth. Add 4–5 tonnes of farm-yard manure (FYM) per acre 15 days before sowing. Level the field for uniform irrigation." },
        { icon: Sprout, title: "3. Sow seeds", detail: "Sow between 5–25 November. Use a seed drill with 22 cm row spacing and 4–5 cm depth. Treat seeds with Carbendazim 50 WP @ 2 g/kg seed." },
        { icon: Droplets, title: "4. First irrigation (CRI)", detail: "Give first irrigation 20–25 days after sowing (crown root initiation). This is the most important irrigation for the entire crop." },
        { icon: Sprout, title: "5. Fertilizer top dressing", detail: "Apply urea 50 kg/acre in two splits — first at CRI irrigation, second at tillering (45 DAS). Add zinc sulphate if leaves turn yellow." },
        { icon: Bug, title: "6. Pest & disease watch", detail: "Scout fields weekly. For yellow rust spray Propiconazole 25 EC @ 1 ml/litre. For aphids spray Imidacloprid 17.8 SL @ 0.3 ml/litre." },
        { icon: Droplets, title: "7. Subsequent irrigations", detail: "Irrigate at tillering, jointing, flowering, milking and dough stage — total 4–6 irrigations depending on rainfall." },
        { icon: Sun, title: "8. Harvest", detail: "Harvest when grains are hard and straw turns golden yellow (moisture ~20%). Use combine harvester or sickle. Thresh within 2–3 days." },
        { icon: Coins, title: "9. Storage & selling", detail: "Dry grains to 10–12% moisture before storage. Check mandi prices on KrishiMitra Market — sell when prices peak." },
      ],
      traditional: [
        { title: "Bullock plough (देसी हल)", img: "https://images.unsplash.com/photo-1571502286049-9fed1e6c25a8?w=800&q=80", text: "Many small farmers in India still use bullock-drawn ploughs for primary tillage. It mixes organic matter gently and uses no diesel." },
        { title: "Broadcast sowing (छिड़काव)", img: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800&q=80", text: "Hand-broadcasting wheat seed after the first rain is a centuries-old technique passed down generations." },
        { title: "Flood irrigation (कियारी)", img: "https://images.unsplash.com/photo-1592982537447-7440770faae0?w=800&q=80", text: "Small bunded plots are flooded one by one — labour intensive but works well with canal water." },
      ],
    },
    {
      id: "rice",
      name: "Rice (धान)",
      emoji: "🍚",
      season: "Kharif (Jun–Nov)",
      duration: "110–140 days",
      yield: "25–30 qtl/acre",
      hero: "https://images.unsplash.com/photo-1568347877321-f8935c7dc5a3?w=1200&q=80",
      description: "Rice is the lifeblood of monsoon agriculture. Whether you transplant or direct-seed, water management is the secret to a great paddy harvest.",
      videoId: "5T-eUEAYNcs",
      steps: [
        { icon: BookOpen, title: "1. Select variety & nursery", detail: "Choose Pusa Basmati 1121, MTU-7029 or Swarna based on region. Use 8 kg seed per acre. Soak 24 hours, then incubate 48 hours for sprouting." },
        { icon: Sprout, title: "2. Raise nursery", detail: "Prepare a wet nursery bed of 1/10th of main field area. Broadcast sprouted seed and keep saturated for 25–30 days." },
        { icon: Tractor, title: "3. Puddle main field", detail: "Flood the main field, then puddle with a rotavator or country plough until it becomes soft mud. Level perfectly." },
        { icon: Sprout, title: "4. Transplant seedlings", detail: "Transplant 25–30 day old seedlings at 20×15 cm spacing, 2–3 seedlings per hill, 2–3 cm depth." },
        { icon: Droplets, title: "5. Water management", detail: "Maintain 2–5 cm standing water during vegetative stage. Drain water 10 days before harvest." },
        { icon: Sprout, title: "6. Fertilizer", detail: "Apply 50 kg urea, 60 kg DAP, 25 kg MOP per acre. Top-dress urea in 2 splits at tillering and panicle initiation." },
        { icon: Bug, title: "7. Pest control", detail: "Watch for stem borer and brown plant hopper. Use pheromone traps + need-based spray of Cartap Hydrochloride." },
        { icon: Sun, title: "8. Harvest", detail: "Harvest when 80% panicles turn straw yellow. Cut, bundle and thresh. Dry grains to 14% moisture." },
        { icon: Coins, title: "9. Selling", detail: "Sell to FCI procurement centres at MSP or in mandi when prices are favourable." },
      ],
      traditional: [
        { title: "SRI method", img: "https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=800&q=80", text: "System of Rice Intensification — single 8-day-old seedlings spaced 25×25 cm with alternate wetting & drying — gives higher yields with less water." },
        { title: "Bullock puddling", img: "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?w=800&q=80", text: "Traditional puddling with a pair of bullocks and a country plough is still common across eastern India." },
        { title: "Manual transplanting", img: "https://images.unsplash.com/photo-1602867741746-6df80f40b3f6?w=800&q=80", text: "Women in groups transplant rice by hand — a labour intensive but precise traditional practice." },
      ],
    },
    {
      id: "tomato",
      name: "Tomato (टमाटर)",
      emoji: "🍅",
      season: "Kharif & Rabi",
      duration: "80–100 days",
      yield: "80–120 qtl/acre",
      hero: "https://images.unsplash.com/photo-1592924357229-91c1c45b8c41?w=1200&q=80",
      description: "A high-value cash crop. With staking, drip irrigation and good pest management, tomato can double a farmer's income in a single season.",
      videoId: "kKK1Y0ggZJM",
      steps: [
        { icon: BookOpen, title: "1. Variety & nursery", detail: "Choose hybrid like Arka Rakshak, Pusa Ruby. Sow 80–100 g seed per acre in raised nursery beds. Cover with shade-net." },
        { icon: Tractor, title: "2. Land preparation", detail: "Plough and form raised beds 90 cm wide, 30 cm high with 60 cm furrows. Apply 8 tonnes FYM per acre." },
        { icon: Sprout, title: "3. Transplant", detail: "Transplant 25–30 day old seedlings at 60×45 cm spacing in evening hours. Water immediately." },
        { icon: Droplets, title: "4. Drip irrigation", detail: "Install drip line — give 4–6 litres/plant/day. Use mulch (silver-black plastic) to conserve moisture and stop weeds." },
        { icon: Sprout, title: "5. Staking & pruning", detail: "Stake with bamboo and tie plants with soft cloth at 30 cm intervals. Remove side shoots up to first flower cluster." },
        { icon: Bug, title: "6. Pest & disease", detail: "Yellow sticky traps for whitefly. Spray Neem oil 5 ml/litre weekly. For blight use Mancozeb 75% WP @ 2.5 g/litre." },
        { icon: Sun, title: "7. Harvest", detail: "Start harvesting 70–80 days after transplant. Pick fruits at breaker stage for distant markets, full red for local sale." },
        { icon: Coins, title: "8. Grading & selling", detail: "Grade by size and colour. Use plastic crates instead of jute bags to reduce damage. Sell daily for best price." },
      ],
      traditional: [
        { title: "Bamboo staking (बांस की टेक)", img: "https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=800&q=80", text: "Local bamboo poles tied in a triangle support each plant — cheap, sustainable and widely used in India." },
        { title: "Neem leaf spray", img: "https://images.unsplash.com/photo-1611329857570-f02f340e7378?w=800&q=80", text: "Crushed neem leaves soaked overnight in water make a strong organic pesticide our grandparents used." },
        { title: "Cow-dung mulch", img: "https://images.unsplash.com/photo-1535732759880-bbd5c7265e3f?w=800&q=80", text: "A thin layer of dried cow-dung between rows keeps soil cool and slowly adds nutrients." },
      ],
    },
    {
      id: "cotton",
      name: "Cotton (कपास)",
      emoji: "☁️",
      season: "Kharif (Jun–Jan)",
      duration: "160–180 days",
      yield: "8–12 qtl/acre",
      hero: "https://images.unsplash.com/photo-1599320330571-ffb6b1a2d6e1?w=1200&q=80",
      description: "India's white gold. Bt cotton with drip irrigation gives the best results in rainfed and irrigated tracts of Maharashtra, Gujarat and Telangana.",
      videoId: "QbBVS-9hSrI",
      steps: [
        { icon: BookOpen, title: "1. Seed selection", detail: "Use Bt cotton hybrid suited to your zone (RCH-2 BG-II, Bunny BG-II). 450 g seed per acre. Treat with Imidacloprid." },
        { icon: Tractor, title: "2. Land prep", detail: "Deep plough once in summer to expose pupae. Two harrowings before sowing. Apply 4 tonnes FYM per acre." },
        { icon: Sprout, title: "3. Sowing", detail: "Sow June–July with first monsoon at 90×45 cm (rainfed) or 120×60 cm (irrigated). Dibble 2 seeds per hill 3 cm deep." },
        { icon: Sprout, title: "4. Thinning & gap-filling", detail: "Thin to one healthy plant per hill after 20 days. Fill gaps with transplanted seedlings." },
        { icon: Droplets, title: "5. Irrigation", detail: "Critical stages — squaring (45 DAS), flowering (75 DAS), boll formation (100 DAS). Avoid water stress at flowering." },
        { icon: Bug, title: "6. Pink bollworm management", detail: "Install 5 pheromone traps/acre. Spray as per ETL with Profenofos or Emamectin. Destroy old stalks after harvest." },
        { icon: Sun, title: "7. Picking", detail: "3–4 pickings at 15-day intervals starting 120 DAS. Pick only fully open dry bolls in morning hours." },
        { icon: Coins, title: "8. Selling", detail: "Sell to CCI at MSP or private ginning mills. Keep clean — avoid mixing trash for higher staple grade." },
      ],
      traditional: [
        { title: "Inter-cropping with pulses", img: "https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=800&q=80", text: "Traditional Marathwada farmers grow tur (pigeon pea) every 6th row of cotton — adds nitrogen and gives extra income." },
        { title: "Hand picking", img: "https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=800&q=80", text: "Cotton is still hand-picked across India — women pick 30–40 kg per day, ensuring only clean bolls go in the bag." },
        { title: "Stalk destruction", img: "https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=800&q=80", text: "Burning or shredding old cotton stalks after harvest breaks the pest life-cycle — a traditional practice now mandated by law." },
      ],
    },
  ],
  hi: [
    {
      id: "wheat",
      name: "गेहूँ (Wheat)",
      emoji: "🌾",
      season: "रबी (अक्टूबर-अप्रैल)",
      duration: "120–150 दिन",
      yield: "18–22 क्विंटल/एकड़",
      hero: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=1200&q=80",
      description: "गेहूं भारत का सबसे महत्वपूर्ण रबी अनाज है। अच्छे बीज, समय पर बुवाई और 4-5 सिंचाइयों के साथ, आप लगभग 4 महीनों में एक स्वस्थ फसल काट सकते हैं।",
      videoId: "PD3Z9q1eYjE",
      steps: [
        { icon: BookOpen, title: "1. बीज की किस्म चुनें", detail: "अपने क्षेत्र के अनुकूल प्रमाणित किस्म चुनें — HD-2967, PBW-550 या DBW-187। कृषि विज्ञान केंद्र (KVK) या अधिकृत डीलर से प्रति एकड़ 40 किलोग्राम बीज खरीदें।" },
        { icon: Tractor, title: "2. खेत तैयार करें", detail: "मिट्टी को महीन बनाने के लिए 2-3 बार जुताई करें। बुवाई से 15 दिन पहले प्रति एकड़ 4-5 टन गोबर की सड़ी खाद (FYM) डालें। समान सिंचाई के लिए खेत को समतल करें।" },
        { icon: Sprout, title: "3. बुवाई करें", detail: "5-25 नवंबर के बीच बुवाई करें। 22 सेमी कतार की दूरी और 4-5 सेमी गहराई पर सीड ड्रिल का उपयोग करें। बीजों को कार्बेन्डाजिम 50 WP @ 2 ग्राम/किलोग्राम बीज से उपचारित करें।" },
        { icon: Droplets, title: "4. पहली सिंचाई (CRI)", detail: "बुवाई के 20-25 दिन बाद (मुकुट जड़ बनने के समय) पहली सिंचाई करें। यह पूरी फसल के लिए सबसे महत्वपूर्ण सिंचाई है।" },
        { icon: Sprout, title: "5. यूरिया का छिड़काव", detail: "प्रति एकड़ 50 किलोग्राम यूरिया दो भागों में डालें — पहला पहली सिंचाई पर, दूसरा कल्ले निकलने (45 दिन) पर। पत्तियाँ पीली होने पर जिंक सल्फेट डालें।" },
        { icon: Bug, title: "6. कीट और रोग नियंत्रण", detail: "साप्ताहिक रूप से खेतों की निगरानी करें। पीला रतुआ रोग के लिए प्रोपिकोनाज़ोल 25 EC @ 1 मिली/लीटर स्प्रे करें। चेपा कीट के लिए इमिडाक्लोप्रिड 17.8 SL @ 0.3 मिली/लीटर स्प्रे करें।" },
        { icon: Droplets, title: "7. बाद की सिंचाई", detail: "कल्ले निकलने, गांठे बनने, फूल आने, दाना भरने और पकने के चरणों पर सिंचाई करें — बारिश के आधार पर कुल 4-6 सिंचाई।" },
        { icon: Sun, title: "8. फसल कटाई", detail: "कटाई तब करें जब दाने कड़े हो जाएं और भूसा सुनहरा पीला हो जाए (नमी ~20%)। कंबाइन हार्वेस्टर या दरांती का उपयोग करें। 2-3 दिनों के भीतर मड़ाई करें।" },
        { icon: Coins, title: "9. भंडारण और बिक्री", detail: "भंडारण से पहले दानों को 10-12% नमी तक सुखाएं। कृषिमित्र बाजार पर मंडी भाव जांचें — भाव अधिकतम होने पर बेचें।" },
      ],
      traditional: [
        { title: "देसी हल (Bullock plough)", img: "https://images.unsplash.com/photo-1571502286049-9fed1e6c25a8?w=800&q=80", text: "भारत में कई छोटे किसान अभी भी प्राथमिक जुताई के लिए बैलों द्वारा खींचे जाने वाले देसी हलों का उपयोग करते हैं। यह जैविक पदार्थों को धीरे से मिलाता है और इसमें डीजल का उपयोग नहीं होता।" },
        { title: "छिड़काव बुवाई (Broadcasting)", img: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800&q=80", text: "पहली बारिश के बाद हाथ से गेहूं के बीजों का छिड़काव करना सदियों पुरानी तकनीक है जो पीढ़ियों से चली आ रही है।" },
        { title: "कियारी सिंचाई (Flood irrigation)", img: "https://images.unsplash.com/photo-1592982537447-7440770faae0?w=800&q=80", text: "खेत को छोटे-छोटे हिस्सों या क्यारियों में बांटकर एक-एक करके पानी से भरा जाता है — इसमें मेहनत अधिक लगती है लेकिन यह नहर के पानी के साथ अच्छा काम करता है।" },
      ],
    },
    {
      id: "rice",
      name: "धान / चावल (Rice)",
      emoji: "🍚",
      season: "खरीफ (जून-नवंबर)",
      duration: "110–140 दिन",
      yield: "25–30 क्विंटल/एकड़",
      hero: "https://images.unsplash.com/photo-1568347877321-f8935c7dc5a3?w=1200&q=80",
      description: "चावल मानसून की कृषि की जीवनरेखा है। चाहे आप रोपाई करें या सीधी बुवाई, बेहतर धान की फसल के लिए जल प्रबंधन ही मुख्य रहस्य है।",
      videoId: "5T-eUEAYNcs",
      steps: [
        { icon: BookOpen, title: "1. किस्म और नर्सरी का चयन", detail: "क्षेत्र के अनुसार पूसा बासमती 1121, MTU-7029 या स्वर्णा चुनें। प्रति एकड़ 8 किलोग्राम बीज का उपयोग करें। बीज को 24 घंटे भिगोएँ, फिर अंकुरण के लिए 48 घंटे रखें।" },
        { icon: Sprout, title: "2. नर्सरी तैयार करना", detail: "मुख्य खेत के 1/10वें हिस्से में गीली नर्सरी क्यारी तैयार करें। अंकुरित बीजों का छिड़काव करें और 25-30 दिनों तक नमी बनाए रखें।" },
        { icon: Tractor, title: "3. मुख्य खेत की कद्दू (Puddling) करना", detail: "मुख्य खेत में पानी भरें, फिर रोटावेटर या देसी हल से कद्दू (कादो) करें जब तक कि मिट्टी मुलायम कीचड़ न बन जाए। इसे अच्छी तरह समतल करें।" },
        { icon: Sprout, title: "4. पौधों की रोपाई", detail: "नर्सरी के 25-30 दिन पुराने पौधों को 20×15 सेमी की दूरी पर, प्रति स्थान 2-3 पौधे, 2-3 सेमी की गहराई पर रोपें।" },
        { icon: Droplets, title: "5. जल प्रबंधन", detail: "वानस्पतिक अवस्था के दौरान खेत में 2-5 सेमी पानी खड़ा रखें। कटाई से 10 दिन पहले खेत का पानी निकाल दें।" },
        { icon: Sprout, title: "6. उर्वरक प्रबंधन", detail: "प्रति एकड़ 50 किग्रा यूरिया, 60 किग्रा डीएपी और 25 किग्रा एमओपी डालें। यूरिया का छिड़काव कल्ले निकलने और बालियाँ बनते समय दो भागों में करें।" },
        { icon: Bug, title: "7. कीट नियंत्रण", detail: "तना छेदक और भूरा पत्ती फुदका कीट पर नज़र रखें। फेरोमोन जाल + आवश्यकतानुसार कार्टाप हाइड्रोक्लोराइड का छिड़काव करें।" },
        { icon: Sun, title: "8. कटाई", detail: "कटाई तब करें जब 80% बालियाँ सुनहरी पीली हो जाएँ। कटाई करें, गट्ठर बनाएँ और मड़ाई करें। अनाज को 14% नमी तक सुखाएं।" },
        { icon: Coins, title: "9. बिक्री", detail: "न्यूनतम समर्थन मूल्य (MSP) पर सरकारी खरीद केंद्रों (FCI) में या अनुकूल भाव होने पर मंडी में बेचें।" },
      ],
      traditional: [
        { title: "श्री विधि (SRI Method)", img: "https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=800&q=80", text: "चावल सघनीकरण की प्रणाली — बारी-बारी से गीला और सूखा रखते हुए 8 दिन पुराने सिंगल पौधों को 25×25 सेमी पर रोपा जाता है। इससे कम पानी में अधिक उपज मिलती है।" },
        { title: "बैलों द्वारा कद्दू करना", img: "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?w=800&q=80", text: "पूर्वी भारत में बैलों की जोड़ी और देसी हल से पारंपरिक कद्दू (कादो) करना आज भी काफी आम है।" },
        { title: "हाथ से रोपाई", img: "https://images.unsplash.com/photo-1602867741746-6df80f40b3f6?w=800&q=80", text: "महिलाएं समूहों में हाथ से धान की रोपाई करती हैं — यह अत्यधिक श्रमसाध्य लेकिन सटीक पारंपरिक पद्धति है।" },
      ],
    },
    {
      id: "tomato",
      name: "टमाटर (Tomato)",
      emoji: "🍅",
      season: "खरीफ और रबी",
      duration: "80–100 दिन",
      yield: "80–120 क्विंटल/एकड़",
      hero: "https://images.unsplash.com/photo-1592924357229-91c1c45b8c41?w=1200&q=80",
      description: "एक उच्च मूल्य वाली नकदी फसल। स्टैकिंग (सहारा देना), ड्रिप सिंचाई और अच्छे कीट प्रबंधन के साथ टमाटर की फसल एक ही सीजन में किसान की आय दोगुनी कर सकती है।",
      videoId: "kKK1Y0ggZJM",
      steps: [
        { icon: BookOpen, title: "1. किस्म और नर्सरी", detail: "अर्क रक्षक, पूसा रूबी जैसी हाइब्रिड किस्म चुनें। उठी हुई नर्सरी क्यारियों में प्रति एकड़ 80-100 ग्राम बीज बोएं। इसे शेड-नेट से ढकें।" },
        { icon: Tractor, title: "2. खेत की तैयारी", detail: "जुताई करें और 90 सेमी चौड़ी, 30 सेमी ऊंची क्यारियां बनाएं जिसमें 60 सेमी की नालियां हों। प्रति एकड़ 8 टन गोबर की खाद डालें।" },
        { icon: Sprout, title: "3. रोपाई", detail: "नर्सरी के 25-30 दिन पुराने पौधों को शाम के समय 60×45 सेमी की दूरी पर रोपें। तुरंत पानी दें।" },
        { icon: Droplets, title: "4. ड्रिप सिंचाई", detail: "ड्रिप लाइन स्थापित करें — प्रति पौधे प्रतिदिन 4-6 लीटर पानी दें। नमी बनाए रखने और खरपतवार रोकने के लिए मल्चिंग (सिल्वर-ब्लैक प्लास्टिक) का उपयोग करें।" },
        { icon: Sprout, title: "5. सहारा देना और छंटाई", detail: "बांस से पौधों को सहारा दें और 30 सेमी के अंतराल पर सूती धागे से बांधें। पहले फूलों के गुच्छे तक की साइड शाखाओं को हटा दें।" },
        { icon: Bug, title: "6. कीट और रोग नियंत्रण", detail: "सफेद मक्खी के लिए पीले चिपचिपे जाल लगाएं। साप्ताहिक रूप से 5 मिली/लीटर नीम के तेल का छिड़काव करें। झुलसा रोग के लिए मैन्कोजेब 75% WP @ 2.5 ग्राम/लीटर का छिड़काव करें।" },
        { icon: Sun, title: "7. फलों की तुड़ाई", detail: "रोपाई के 70-80 दिन बाद तुड़ाई शुरू करें। दूर के बाजारों के लिए अधपके फल और स्थानीय बिक्री के लिए पूरे लाल फल तोड़ें।" },
        { icon: Coins, title: "8. ग्रेडिंग और बिक्री", detail: "आकार और रंग के आधार पर टमाटरों की छँटाई करें। नुकसान कम करने के लिए जूट के थैलों के बजाय प्लास्टिक क्रेट का उपयोग करें। सर्वोत्तम मूल्य के लिए प्रतिदिन बेचें।" },
      ],
      traditional: [
        { title: "बांस की टेक (Bamboo staking)", img: "https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=800&q=80", text: "त्रिभुज आकार में बंधे स्थानीय बांस के खंभे प्रत्येक पौधे को सहारा देते हैं — यह सस्ता, टिकाऊ और भारत में व्यापक रूप से उपयोग किया जाता है।" },
        { title: "नीम की पत्ती का स्प्रे", img: "https://images.unsplash.com/photo-1611329857570-f02f340e7378?w=800&q=80", text: "नीम की कुचली हुई पत्तियों को रात भर पानी में भिगोकर बनाया गया स्प्रे एक मजबूत जैविक कीटनाशक है जिसका उपयोग हमारे पूर्वज करते थे।" },
        { title: "गोबर की मल्चिंग", img: "https://images.unsplash.com/photo-1535732759880-bbd5c7265e3f?w=800&q=80", text: "कतारों के बीच सूखे गोबर की एक पतली परत मिट्टी को ठंडा रखती है और धीरे-धीरे पोषक तत्व प्रदान करती है।" },
      ],
    },
    {
      id: "cotton",
      name: "कपास (Cotton)",
      emoji: "☁️",
      season: "खरीफ (जून-जनवरी)",
      duration: "160–180 दिन",
      yield: "8–12 क्विंटल/एकड़",
      hero: "https://images.unsplash.com/photo-1599320330571-ffb6b1a2d6e1?w=1200&q=80",
      description: "भारत का सफेद सोना। ड्रिप सिंचाई के साथ बीटी कपास महाराष्ट्र, गुजरात और तेलंगाना के सिंचित और असिंचित क्षेत्रों में सर्वोत्तम परिणाम देती है।",
      videoId: "QbBVS-9hSrI",
      steps: [
        { icon: BookOpen, title: "1. बीज का चयन", detail: "अपने क्षेत्र के अनुकूल बीटी कपास हाइब्रिड (RCH-2 BG-II, Bunny BG-II) का उपयोग करें। प्रति एकड़ 450 ग्राम बीज। इमिडाक्लोप्रिड से उपचारित करें।" },
        { icon: Tractor, title: "2. खेत की तैयारी", detail: "शत्रु कीटों को नष्ट करने के लिए गर्मियों में एक बार गहरी जुताई करें। बुवाई से पहले दो बार हैरो चलाएं। प्रति एकड़ 4 टन गोबर की खाद डालें।" },
        { icon: Sprout, title: "3. बुवाई", detail: "पहली मानसूनी बारिश के साथ जून-जुलाई में 90×45 सेमी (असिंचित) या 120×60 सेमी (ससिंचित) की दूरी पर बुवाई करें। प्रति गड्ढा 2 बीज 3 सेमी गहरे रोपें।" },
        { icon: Sprout, title: "4. छंटाई और गैप-फिलिंग", detail: "बुवाई के 20 दिन बाद प्रति गड्ढा एक ही स्वस्थ पौधा छोड़ें। खाली जगहों को नर्सरी से लाए गए पौधों से भरें।" },
        { icon: Droplets, title: "5. सिंचाई", detail: "महत्वपूर्ण चरण — फूल की कलियाँ बनते समय (45 दिन), फूल आते समय (75 दिन) और डोडे बनते समय (100 दिन)। फूल आने के समय पानी की कमी न होने दें।" },
        { icon: Bug, title: "6. गुलाबी सूंडी (Pink Bollworm) नियंत्रण", detail: "गुलाबी सूंडी की निगरानी के लिए प्रति एकड़ 5 फेरोमोन जाल लगाएं। प्रोफेनोफोस या एमामेक्टिन के साथ छिड़काव करें। कटाई के बाद पुराने डंठल नष्ट कर दें।" },
        { icon: Sun, title: "7. चुनाई (Picking)", detail: "120 दिन के बाद से शुरू कर 15-15 दिनों के अंतराल पर 3-4 बार चुनाई करें। सुबह के समय केवल पूरी तरह से खिले और सूखे डोडे ही चुनें।" },
        { icon: Coins, title: "8. बिक्री", detail: "न्यूनतम समर्थन मूल्य (MSP) पर सीसीआई (CCI) को या निजी जिनिंग मिलों को बेचें। बेहतर ग्रेडिंग के लिए कचरा मिलाने से बचें।" },
      ],
      traditional: [
        { title: "दालों के साथ सह-फसल (Inter-cropping)", img: "https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=800&q=80", text: "पारंपरिक मराठवाड़ा के किसान कपास की हर छठी कतार में अरहर (तूर) उगाते हैं — यह मिट्टी में नाइट्रोजन जोड़ता है और अतिरिक्त आय देता है।" },
        { title: "हाथ से चुनाई (Hand picking)", img: "https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=800&q=80", text: "भारत भर में कपास की चुनाई आज भी हाथ से की जाती है — महिलाएं प्रतिदिन 30-40 किलो कपास चुनती हैं, जिससे केवल साफ कपास ही एकत्र होता है।" },
        { title: "डंठल नष्ट करना", img: "https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=800&q=80", text: "कटाई के बाद कपास के पुराने डंठलों को नष्ट या कुचल देना कीटों के जीवन-चक्र को तोड़ता है — यह पारंपरिक अभ्यास अब कानूनन अनिवार्य है।" },
      ],
    },
  ],
  mr: [
    {
      id: "wheat",
      name: "गहू (Wheat)",
      emoji: "🌾",
      season: "रब्बी (ऑक्टोबर-एप्रिल)",
      duration: "120–150 दिवस",
      yield: "18–22 क्विंटल/एकर",
      hero: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=1200&q=80",
      description: "गहू हा भारतातील सर्वात महत्त्वाचा रब्बी तृणधान्य पीक आहे. चांगले बियाणे, वेळेवर पेरणी आणि ४-५ सिंचनासह आपण सुमारे ४ महिन्यांत निरोगी पिकाची काढणी करू शकता.",
      videoId: "PD3Z9q1eYjE",
      steps: [
        { icon: BookOpen, title: "१. बियाण्याची जात निवडा", detail: "तुमच्या भागासाठी योग्य असलेली प्रमाणित जात निवडा — HD-2967, PBW-550 किंवा DBW-187. कृषी विज्ञान केंद्र (KVK) किंवा परवानाधारक विक्रेत्याकडून प्रति एकर ४० किलो बियाणे खरेदी करा." },
        { icon: Tractor, title: "२. जमीन तयार करा", detail: "जमीन २-३ वेळा चांगली नांगरून बारीक करा. पेरणीपूर्वी १५ दिवस आधी प्रति एकर ४-५ टन शेणखत (FYM) टाका. पाण्याचे समान वाटप होण्यासाठी शेत समतल करा." },
        { icon: Sprout, title: "३. बियाणे पेरा", detail: "५ ते २५ नोव्हेंबर दरम्यान पेरणी करा. २२ सेमी ओळीतील अंतर आणि ४-५ सेमी खोलीवर सीड ड्रिलचा वापर करा. बियाण्याला कार्बेन्डाझिम ५० WP @ २ ग्रॅम/किलो बियाणे या प्रमाणात चोळा." },
        { icon: Droplets, title: "४. पहिले पाणी (CRI)", detail: "पेरणीनंतर २०-२५ दिवसांनी (मुकुटमुळे फुटण्याच्या वेळी) पहिले पाणी द्या. हे संपूर्ण पिकासाठी अत्यंत महत्त्वाचे पाणी आहे." },
        { icon: Sprout, title: "५. खताचा हप्ता देणे", detail: "प्रति एकर ५० किलो युरिया दोन भागात द्या — पहिला पहिल्या पाण्याच्या वेळी, दुसरा फुटवे येण्याच्या वेळी (४५ दिवसांनी). पाने पिवळी पडल्यास झिंक सल्फेट द्या." },
        { icon: Bug, title: "६. कीड व रोग नियंत्रण", detail: "दर आठवड्याला शेताची पाहणी करा. तांबेरा (Yellow Rust) रोगासाठी प्रोपिकोनाझोल २५ EC @ १ मिली/लीटर फवारा. मावा किडीसाठी इमिडाक्लोप्रिड १७.८ SL @ ०.३ मिली/लीटर फवारा." },
        { icon: Droplets, title: "७. पुढील सिंचन", detail: "फुटवे येणे, कांडी धरणे, फुले येणे, दाणे भरणे आणि दाणे घट्ट होणे या टप्प्यांवर पाणी द्या — पावसाच्या प्रमाणानुसार एकूण ४-६ पाणी." },
        { icon: Sun, title: "८. काढणी", detail: "दाणे घट्ट झाल्यावर आणि पेंढा सोनेरी पिवळा झाल्यावर कापणी करा (ओलावा ~२०%). कंबाइन हार्वेस्टर किंवा विळयाचा वापर करा. २-३ दिवसांत मळणी करा." },
        { icon: Coins, title: "९. साठवणूक आणि विक्री", detail: "साठवण्यापूर्वी दाणे १०-१२% ओलावा येईपर्यंत सुकवून घ्या. कृषीमित्र मार्केटवर बाजार भाव तपासा — दर वाढल्यावर विक्री करा." },
      ],
      traditional: [
        { title: "देशी नांगर (Desi plough)", img: "https://images.unsplash.com/photo-1571502286049-9fed1e6c25a8?w=800&q=80", text: "भारतातील अनेक लहान शेतकरी प्राथमिक मशागतीसाठी आजही बैलांच्या सहाय्याने ओढल्या जाणाऱ्या नांगराचा वापर करतात. हे सेंद्रिय पदार्थ हलक्या हाताने मातीत मिसळते आणि डिझेल लागत नाही." },
        { title: "फेकून पेरणी (Broadcasting)", img: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800&q=80", text: "पहिल्या पावसाच्या ओलाव्यावर हाताने गव्हाचे बियाणे विखुरणे ही पिढ्यानपिढ्या चालत आलेली जुनी पारंपरिक पद्धत आहे." },
        { title: "वाफे सिंचन (Flood irrigation)", img: "https://images.unsplash.com/photo-1592982537447-7440770faae0?w=800&q=80", text: "शेताचे लहान तुकडे किंवा सारे करून एक-एक करून पाणी दिले जाते — ही श्रमप्रधान पद्धत असली तरी कालव्याच्या पाण्यासोबत चांगली चालते." },
      ],
    },
    {
      id: "rice",
      name: "भात / धान (Rice)",
      emoji: "🍚",
      season: "खरीप (जून-नोव्हेंबर)",
      duration: "११०–१४० दिवस",
      yield: "२५–३० क्विंटल/एकर",
      hero: "https://images.unsplash.com/photo-1568347877321-f8935c7dc5a3?w=1200&q=80",
      description: "भात शेती ही मान्सून हंगामाची जीवनवाहिनी आहे. आवण लावून किंवा थेट पेरणी करून, भात उत्पादनात पाणी व्यवस्थापन हाच मुख्य यशस्वी मार्ग आहे.",
      videoId: "5T-eUEAYNcs",
      steps: [
        { icon: BookOpen, title: "१. बियाणे आणि रोपवाटिका निवड", detail: "भागाच्या गरजेनुसार पुसा बासमती ११२१, MTU-७०२९ किंवा स्वर्णा निवडा. प्रति एकर ८ किलो बियाणे वापरा. बियाणे २४ तास पाण्यात भिजवा, नंतर मोड येण्यासाठी ४८ तास ठेवा." },
        { icon: Sprout, title: "२. रोपवाटिका तयार करणे", detail: "मुख्य शेताच्या १/१० व्या भागावर ओळीत रोपवाटिका तयार करा. मोड आलेले बियाणे विखुरून टाका आणि २५-३० दिवस जमिनीतील ओल टिकवून ठेवा." },
        { icon: Tractor, title: "३. मुख्य चिखलणी (Puddling) करणे", detail: "मुख्य शेतात पाणी साठवून ठेवा, नंतर रोटावेटर किंवा नांगराच्या सहाय्याने मातीचा मऊ चिखल होईपर्यंत चिखलणी करा. जमीन व्यवस्थित सपाट करा." },
        { icon: Sprout, title: "४. रोपांची पुनर्लागवड", detail: "रोपवाटिकेतील २५-३० दिवसांची रोपे २०×१५ सेमी अंतरावर, एका ठिकाणी २-३ रोपे, २-३ सेमी खोलीवर लावावीत." },
        { icon: Droplets, title: "५. पाणी व्यवस्थापन", detail: "वाढीच्या टप्प्यात २-५ सेमी पाणी साचवून ठेवा. कापणीच्या १० दिवस आधी शेतातील पाणी पूर्णपणे काढून टाका." },
        { icon: Sprout, title: "६. खत व्यवस्थापन", detail: "प्रति एकर ५० किलो युरिया, ६० किलो डीएपी आणि २५ किलो एमओपी द्या. युरिया फुटवे येताना आणि लोंब्या बाहेर पडताना अशा दोन हप्त्यांत द्या." },
        { icon: Bug, title: "७. कीड नियंत्रण", detail: "खोडकिडा आणि तपकिरी तुडतुडे यांवर बारीक लक्ष ठेवा. फेरोमोन सापळे लावा आणि गरजेनुसार कार्टाप हायड्रोक्लोराईडची फवारणी करा." },
        { icon: Sun, title: "८. काढणी", detail: "८०% लोंब्या सोनेरी पिवळ्या रंगाच्या झाल्यावर कापणी करा. कापणी करून पेंढ्या बांधा आणि मळणी करा. दाणे १४% ओलावा येईपर्यंत सुकवा." },
        { icon: Coins, title: "९. विक्री", detail: "हमीभावाने (MSP) सरकारी खरेदी केंद्रावर किंवा चांगला दर मिळताच स्थानिक बाजार समितीत (APMC) विक्री करा." },
      ],
      traditional: [
        { title: "श्री पद्धत (SRI Method)", img: "https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=800&q=80", text: "भात लागवडीची श्री पद्धत — जमिनीला काही काळ ओले तर काही काळ सुके ठेवून ८ दिवसांची कोवळी रोपे २५×२५ सेमी अंतरावर लावली जातात. कमी पाण्यात जास्त उत्पन्न मिळते." },
        { title: "बैलांच्या सहाय्याने चिखलणी", img: "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?w=800&q=80", text: "दोन बैल आणि देशी नांगर वापरून केली जाणारी पारंपरिक चिखलणी आजही महाराष्ट्रातील कोकण आणि पूर्व विदर्भात मोठ्या प्रमाणावर आढळते." },
        { title: "हाताने पुनर्लागवड (Manual transplanting)", img: "https://images.unsplash.com/photo-1602867741746-6df80f40b3f6?w=800&q=80", text: "महिला शेतमजूर गटाने हाताने भाताची लावणी करतात — हे कष्टाचे काम असले तरी पारंपरिक आणि अचूक आहे." },
      ],
    },
    {
      id: "tomato",
      name: "टोमॅटो (Tomato)",
      emoji: "🍅",
      season: "खरीप आणि रब्बी",
      duration: "८०–१०० दिवस",
      yield: "८०–१२० क्विंटल/एकर",
      hero: "https://images.unsplash.com/photo-1592924357229-91c1c45b8c41?w=1200&q=80",
      description: "एक महत्त्वाचे नगदी पीक. बांधणी (स्टॅकिंग), ठिबक सिंचन आणि योग्य कीड व्यवस्थापन याद्वारे टोमॅटोचे पीक शेतकऱ्याचे उत्पन्न एकाच हंगामात दुप्पट करू शकते.",
      videoId: "kKK1Y0ggZJM",
      steps: [
        { icon: BookOpen, title: "१. जात आणि रोपवाटिका", detail: "अर्का रक्षक, पुसा रुबी यांसारखी संकरित जात निवडा. गादीवाफ्यावर प्रति एकर ८०-१०० ग्रॅम बियाणे पेरा. रोपवाटिका शेड-नेटने झाका." },
        { icon: Tractor, title: "२. जमीन तयार करणे", detail: "नांगरणी करून ९० सेमी रुंद, ३० सेमी उंच आणि ६० सेमीचे सरे (नाल्या) असलेले गादीवाफे बनवा. प्रति एकर ८ टन चांगले कुजलेले शेणखत घाला." },
        { icon: Sprout, title: "३. पुनर्लागवड", detail: "रोपवाटिकेतील २५-३० दिवसांची निरोगी रोपे संध्याकाळच्या वेळी ६०×४५ सेमी अंतरावर लावावीत. लागवडीनंतर लगेच पाणी द्या." },
        { icon: Droplets, title: "४. ठिबक सिंचन (Drip)", detail: "ठिबक सिंचन संच बसवा — प्रति झाड दिवसाला ४-६ लीटर पाणी द्या. ओल टिकवण्यासाठी आणि तण वाढू नये म्हणून मल्चिंग पेपरचा वापर करा." },
        { icon: Sprout, title: "५. बांधणी व छाटणी", detail: "बांबूच्या सहाय्याने झाडांना आधार द्या आणि ३० सेमी अंतरावर सुतळीने बांधा. पहिल्या फुलांच्या घडाखालील बाजूचे फुटवे काढून टाका." },
        { icon: Bug, title: "६. कीड व रोग नियंत्रण", detail: "पांढऱ्या माशीसाठी पिवळे चिकट सापळे लावा. दर आठवड्याला ५ मिली/लीटर नीम तेलाची फवारणी करा. करपा रोगासाठी मँकोझेब ७५% WP @ २.५ ग्रॅम/लीटर फवारा." },
        { icon: Sun, title: "७. काढणी", detail: "लागवडीनंतर ७०-८० दिवसांनी फळे तोडण्यास सुरुवात होते. दूरच्या बाजारासाठी थोडे कच्चे आणि स्थानिक बाजारासाठी पूर्ण लाल झालेले टोमॅटो तोडावेत." },
        { icon: Coins, title: "८. प्रतवारी आणि विक्री", detail: "टोमॅटोच्या आकार व रंगानुसार प्रतवारी करा. नुकसान टाळण्यासाठी क्रेटचा वापर करा. चांगल्या भावासाठी दररोज विक्री करा." },
      ],
      traditional: [
        { title: "बांबूची टेक (Bamboo staking)", img: "https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=800&q=80", text: "त्रिभुज आकारात बांधलेले स्थानिक बांबूचे खांब प्रत्येक झाडाला आधार देतात — ही कमी खर्चाची, शाश्वत पद्धत महाराष्ट्रात मोठ्या प्रमाणावर वापरली जाते." },
        { title: "कडुलिंबाचा अर्क", img: "https://images.unsplash.com/photo-1611329857570-f02f340e7378?w=800&q=80", text: "बारीक केलेला कडुलिंबाचा पाला रात्रभर पाण्यात भिजवून तयार केलेला अर्क हा एक अत्यंत प्रभावी आणि पारंपरिक सेंद्रिय कीटकनाशक आहे." },
        { title: "शेणखताचे आच्छादन", img: "https://images.unsplash.com/photo-1535732759880-bbd5c7265e3f?w=800&q=80", text: "ओळींच्या मध्ये वाळलेल्या शेणखताचा बारीक थर दिल्याने जमिनीतील ओल टिकून राहते आणि पिकाला हळूहळू पोषण मिळते." },
      ],
    },
    {
      id: "cotton",
      name: "कापूस (Cotton)",
      emoji: "☁️",
      season: "खरीप (जून-जानेवारी)",
      duration: "१६०–१८० दिवस",
      yield: "८–१२ क्विंटल/एकर",
      hero: "https://images.unsplash.com/photo-1599320330571-ffb6b1a2d6e1?w=1200&q=80",
      description: "महाराष्ट्राचे पांढरे सोने. ठिबक सिंचनावर बीटी कापसाची लागवड विदर्भ, खानदेश आणि मराठवाड्याच्या कोरडवाहू व बागायती भागात सर्वोत्तम उत्पन्न देते.",
      videoId: "QbBVS-9hSrI",
      steps: [
        { icon: BookOpen, title: "१. बियाणे निवड", detail: "तुमच्या विभागासाठी शिफारस केलेले बीटी बियाणे (RCH-2 BG-II किंवा Bunny BG-II) वापरावे. प्रति एकर ४५० ग्रॅम बियाणे. कीड संरक्षणासाठी बियाण्याला प्रक्रिया करावी." },
        { icon: Tractor, title: "२. पूर्वमशागत", detail: "कीटकांच्या कोशांना नष्ट करण्यासाठी उन्हाळ्यात एकदा खोल नांगरणी करावी. पेरणीपूर्वी दोन वेळा कुळवाच्या पाळ्या द्याव्यात. प्रति एकर ४ टन शेणखत टाकावे." },
        { icon: Sprout, title: "३. लागवड / टोकण", detail: "पहिल्या चांगल्या पावसासह जून-जुलैमध्ये ९०×४५ सेमी (कोरडवाहू) किंवा १२०×६० सेमी (बागायती) अंतरावर लागवड करावी. एका ठिकाणी २ बिया ३ सेमी खोलीवर टोकाव्यात." },
        { icon: Sprout, title: "४. विरळणी आणि नांगे भरणे", detail: "पेरणीनंतर २० दिवसांनी एका ठिकाणी एकच निरोगी रोप ठेवून विरळणी करावी. रिकाम्या जागी नवीन रोपे लावून नांगे भरावेत." },
        { icon: Droplets, title: "५. पाणी व्यवस्थापन", detail: "महत्त्वाचे टप्पे — पात्या धरताना (४५ दिवस), फुले येताना (७५ दिवस) आणि बोंडे धरताना (१०० दिवस). फुले येण्याच्या वेळी झाडाला पाण्याचा ताण पडू देऊ नये." },
        { icon: Bug, title: "६. गुलाबी बोंडअळी (Pink Bollworm) नियंत्रण", detail: "बोंडअळीच्या देखरेखीसाठी प्रति एकर ५ कामगंध (फेरोमोन) सापळे लावावेत. आर्थिक नुकसान पातळी ओलांडल्यास प्रोफेनोफॉस किंवा एमामेक्टिनची फवारणी करावी." },
        { icon: Sun, title: "७. वेचणी (Picking)", detail: "१२० दिवसांनंतर १५ दिवसांच्या अंतराने ३-४ वेचण्या कराव्यात. सकाळी उमललेली आणि कोरडी बोंडेच वेचावीत." },
        { icon: Coins, title: "८. विक्री", detail: "हमीभावाने (MSP) कापूस महामंडळाला (CCI) किंवा खाजगी जिनिंग मिलला विकावा. जास्त भावासाठी वेचणी करताना पालापाचोळा मिसळू देऊ नका." },
      ],
      traditional: [
        { title: "आंतरपीक पद्धती (Inter-cropping)", img: "https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=800&q=80", text: "पारंपरिक मराठवाड्यात कापसाच्या दर ६ व्या ओळीला तूर किंवा मूग लावला जातो — यामुळे जमिनीला नत्र मिळते आणि अतिरिक्त उत्पन्न मिळते." },
        { title: "हाताने वेचणी", img: "https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=800&q=80", text: "महाराष्ट्रात कापूस वेचणी पूर्णपणे हाताने केली जाते — मजूर दिवसाला ३०-४० किलो स्वच्छ कापूस वेचतात, ज्यामुळे कापसाचा दर्जा उत्तम राहतो." },
        { title: "कापूस पऱ्हाट्या नष्ट करणे", img: "https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=800&q=80", text: "हंगाम संपल्यावर कापसाच्या पऱ्हाट्या रोटाव्हेटरने जमिनीत कुजवून किंवा नष्ट करून बोंडअळीचा जीवनक्रम तोडला जातो — हे कीड नियंत्रणासाठी महत्त्वाचे आहे." },
      ],
    },
  ],
};
