export interface Scheme {
  id: string;
  name: string;
  shortName: string;
  category: string;
  benefit: string;
  amount: string;
  eligibility: string[];
  documents: string[];
  howToApply: string[];
  states: string;
  website: string;
  color: string;
}

export const SCHEMES_DATA: Record<string, Scheme[]> = {
  en: [
    {
      id: "pmkisan",
      name: "PM Kisan Samman Nidhi",
      shortName: "PM-KISAN",
      category: "Income Support",
      benefit: "Direct income support to all landholding farmers",
      amount: "₹6,000 per year in 3 equal installments of ₹2,000",
      eligibility: [
        "All landholding farmer families in India",
        "Land should be in farmer's name or family member's name",
        "Institutional landholders not eligible",
        "Government employees and income tax payers not eligible",
      ],
      documents: ["Aadhaar Card", "Land Records (7/12 or Khasra-Khatauni)", "Bank account linked to Aadhaar", "Mobile number"],
      howToApply: [
        "Visit pmkisan.gov.in or nearest CSC/VLE",
        "Click 'New Farmer Registration'",
        "Enter Aadhaar number and state",
        "Fill farm and bank details",
        "Submit and note the registration number",
      ],
      states: "All India",
      website: "https://pmkisan.gov.in",
      color: "leaf",
    },
    {
      id: "pmfby",
      name: "Pradhan Mantri Fasal Bima Yojana",
      shortName: "PMFBY",
      category: "Insurance",
      benefit: "Crop insurance covering losses due to natural calamities, pests and diseases",
      amount: "Premium: 2% for Kharif, 1.5% for Rabi, 5% for commercial crops. Government pays the rest.",
      eligibility: [
        "All farmers (loanee and non-loanee) growing notified crops",
        "Both tenant and sharecropper farmers eligible",
        "Must have valid land records or tenancy agreement",
      ],
      documents: ["Aadhaar Card", "Land Records / Tenancy agreement", "Bank Passbook", "Sowing Certificate from Patwari", "Mobile number"],
      howToApply: [
        "Visit your bank, CSC or insurance company",
        "Fill PMFBY application form",
        "Submit sowing certificate and land records",
        "Pay the applicable premium amount",
        "Receive policy document",
      ],
      states: "All India",
      website: "https://pmfby.gov.in",
      color: "sky",
    },
    {
      id: "kcc",
      name: "Kisan Credit Card",
      shortName: "KCC",
      category: "Credit",
      benefit: "Short-term credit for agricultural needs at subsidized interest rate of 4% per annum",
      amount: "Credit limit based on landholding and crop — typically ₹1.60 lakh to ₹3 lakh",
      eligibility: [
        "All farmers — individual, joint borrowers, tenant farmers, SHGs",
        "No upper limit on landholding",
        "Existing KCC holders can get enhanced limit",
      ],
      documents: ["Aadhaar Card", "PAN Card", "Land Records", "Passport size photo", "Bank account details"],
      howToApply: [
        "Visit nearest bank branch (any public, private or cooperative bank)",
        "Ask for KCC application form",
        "Fill form with land and cropping details",
        "Bank will inspect land and sanction limit",
        "Receive KCC and activate with PIN",
      ],
      states: "All India",
      website: "https://www.india.gov.in/spotlight/kisan-credit-card",
      color: "wheat",
    },
    {
      id: "shc",
      name: "Soil Health Card Scheme",
      shortName: "SHC",
      category: "Soil & Organic",
      benefit: "Free soil testing and personalized fertilizer recommendations every 2 years",
      amount: "Free service — No cost to farmer",
      eligibility: ["All farmers in India", "Both small and large landholders"],
      documents: ["Aadhaar Card", "Land Records", "Mobile number"],
      howToApply: [
        "Contact local agriculture department or Krishi Vigyan Kendra",
        "Provide soil sample (200g from your field at 6-inch depth)",
        "Samples tested at state soil testing labs",
        "Receive Soil Health Card within 30 days",
        "Card shows NPK levels and recommended fertilizers",
      ],
      states: "All India",
      website: "https://soilhealth.dac.gov.in",
      color: "soil",
    },
    {
      id: "enam",
      name: "e-National Agriculture Market",
      shortName: "e-NAM",
      category: "Market",
      benefit: "Online trading platform to sell crops directly at better prices across mandis",
      amount: "0% commission for farmers (buyers pay 0.3%)",
      eligibility: ["Any farmer registered with their local APMC mandi", "Crops must be in the list of notified commodities"],
      documents: ["Aadhaar Card", "Bank Account details", "APMC mandi registration"],
      howToApply: [
        "Register at enam.gov.in or visit your local mandi",
        "Submit Aadhaar and bank details",
        "Get e-NAM ID and password",
        "List your produce with quantity and grade",
        "Buyers across India can bid — accept best price",
      ],
      states: "22 states, 1000+ mandis",
      website: "https://enam.gov.in",
      color: "terracotta",
    },
    {
      id: "pkvy",
      name: "Paramparagat Krishi Vikas Yojana",
      shortName: "PKVY",
      category: "Soil & Organic",
      benefit: "Financial support to adopt organic farming and get certified",
      amount: "₹50,000 per hectare over 3 years (₹31,000 direct to farmer)",
      eligibility: [
        "Farmers willing to convert to organic farming",
        "Must form a cluster of minimum 20 farmers",
        "Minimum 20 hectares of contiguous land",
      ],
      documents: ["Aadhaar Card", "Land Records", "Group/Cluster formation certificate"],
      howToApply: [
        "Form a group of 20+ farmers in your village",
        "Approach district agriculture officer",
        "Submit group application with land records",
        "Attend training sessions by government",
        "Receive certification and support over 3 years",
      ],
      states: "All India",
      website: "https://pgsindia-ncof.gov.in",
      color: "primary",
    },
    {
      id: "raftaar",
      name: "Rashtriya Krishi Vikas Yojana",
      shortName: "RKVY",
      category: "Technology",
      benefit: "Subsidies for farm mechanization, infrastructure, and technology adoption",
      amount: "50–80% subsidy on farm machinery and equipment",
      eligibility: ["Individual farmers and FPOs", "Priority to SC/ST farmers (80% subsidy)", "Small and marginal farmers prioritized"],
      documents: ["Aadhaar Card", "Land Records", "Income Certificate", "Quotation for equipment"],
      howToApply: [
        "Visit district agriculture office",
        "Apply for specific machinery subsidy",
        "Submit land and income documents",
        "Purchase equipment from approved dealer",
        "Submit purchase invoice to claim subsidy",
      ],
      states: "All India (state-wise quotas)",
      website: "https://rkvy.nic.in",
      color: "wheat",
    },
  ],
  hi: [
    {
      id: "pmkisan",
      name: "पीएम किसान सम्मान निधि",
      shortName: "PM-KISAN",
      category: "Income Support",
      benefit: "सभी भूमिधारक किसान परिवारों को प्रत्यक्ष आय सहायता",
      amount: "₹6,000 प्रति वर्ष ₹2,000 की 3 समान किश्तों में",
      eligibility: [
        "भारत के सभी भूमिधारक किसान परिवार",
        "भूमि किसान या उसके परिवार के सदस्य के नाम पर होनी चाहिए",
        "संस्थागत भूमिधारक इसके पात्र नहीं हैं",
        "सरकारी कर्मचारी और आयकर दाता इसके पात्र नहीं हैं",
      ],
      documents: ["आधार कार्ड", "भूमि रिकॉर्ड (7/12 या खसरा-खतौनी)", "आधार से लिंक बैंक खाता", "मोबाइल नंबर"],
      howToApply: [
        "pmkisan.gov.in पर जाएं या नजदीकी CSC/VLE केंद्र पर जाएं",
        "'New Farmer Registration' पर क्लिक करें",
        "अपना आधार नंबर और राज्य दर्ज करें",
        "खेत और बैंक विवरण भरें",
        "फॉर्म जमा करें और पंजीकरण संख्या नोट करें",
      ],
      states: "पूरे भारत में",
      website: "https://pmkisan.gov.in",
      color: "leaf",
    },
    {
      id: "pmfby",
      name: "प्रधानमंत्री फसल बीमा योजना",
      shortName: "PMFBY",
      category: "Insurance",
      benefit: "प्राकृतिक आपदाओं, कीटों और बीमारियों के कारण होने वाले नुकसान के लिए फसल बीमा",
      amount: "प्रीमियम: खरीफ के लिए 2%, रबी के लिए 1.5%, वाणिज्यिक फसलों के लिए 5%। बाकी भुगतान सरकार करती है।",
      eligibility: [
        "अधिसूचित फसलें उगाने वाले सभी किसान (ऋणी और गैर-ऋणी)",
        "किराएदार और बटाईदार किसान दोनों पात्र हैं",
        "वैध भूमि रिकॉर्ड या किराएदारी समझौता होना चाहिए",
      ],
      documents: ["आधार कार्ड", "भूमि रिकॉर्ड / किराएदारी समझौता", "बैंक पासबुक", "पटवारी द्वारा जारी बुवाई प्रमाण पत्र", "मोबाइल नंबर"],
      howToApply: [
        "अपने बैंक, सीएससी (CSC) या बीमा कंपनी पर जाएं",
        "PMFBY आवेदन पत्र भरें",
        "बुवाई प्रमाण पत्र और भूमि रिकॉर्ड जमा करें",
        "लागू प्रीमियम राशि का भुगतान करें",
        "बीमा पॉलिसी दस्तावेज प्राप्त करें",
      ],
      states: "पूरे भारत में",
      website: "https://pmfby.gov.in",
      color: "sky",
    },
    {
      id: "kcc",
      name: "किसान क्रेडिट कार्ड",
      shortName: "KCC",
      category: "Credit",
      benefit: "4% वार्षिक की रियायती ब्याज दर पर अल्पकालिक कृषि आवश्यकताओं के लिए ऋण",
      amount: "ऋण सीमा भूमि और फसल के आधार पर — आमतौर पर ₹1.60 लाख से ₹3 लाख",
      eligibility: [
        "सभी किसान — व्यक्तिगत, संयुक्त उधारकर्ता, किराएदार किसान, स्वयं सहायता समूह (SHG)",
        "भूमि जोतने की कोई ऊपरी सीमा नहीं",
        "मौजूदा केसीसी धारक बढ़ी हुई ऋण सीमा प्राप्त कर सकते हैं",
      ],
      documents: ["आधार कार्ड", "पैन कार्ड", "भूमि रिकॉर्ड (खतौनी)", "पासपोर्ट साइज फोटो", "बैंक खाता विवरण"],
      howToApply: [
        "नजदीकी बैंक शाखा (कोई भी सार्वजनिक, निजी या सहकारी बैंक) पर जाएं",
        "KCC आवेदन पत्र मांगें",
        "भूमि और फसल विवरण के साथ फॉर्म भरें",
        "बैंक भूमि का निरीक्षण करेगा और ऋण सीमा मंजूर करेगा",
        "केसीसी प्राप्त करें और पिन के साथ सक्रिय करें",
      ],
      states: "पूरे भारत में",
      website: "https://www.india.gov.in/spotlight/kisan-credit-card",
      color: "wheat",
    },
    {
      id: "shc",
      name: "मृदा स्वास्थ्य कार्ड योजना",
      shortName: "SHC",
      category: "Soil & Organic",
      benefit: "हर 2 साल में मुफ्त मिट्टी परीक्षण और व्यक्तिगत उर्वरक सिफारिशें",
      amount: "मुफ्त सेवा — किसानों के लिए कोई शुल्क नहीं",
      eligibility: ["भारत के सभी किसान", "छोटे और बड़े दोनों भूमिधारक पात्र हैं"],
      documents: ["आधार कार्ड", "भूमि रिकॉर्ड", "मोबाइल नंबर"],
      howToApply: [
        "स्थानीय कृषि विभाग या कृषि विज्ञान केंद्र (KVK) से संपर्क करें",
        "मिट्टी का नमूना प्रदान करें (अपने खेत से 6 इंच की गहराई से 200 ग्राम मिट्टी)",
        "नमूनों का परीक्षण राज्य की मिट्टी परीक्षण प्रयोगशालाओं में किया जाएगा",
        "30 दिनों के भीतर मृदा स्वास्थ्य कार्ड प्राप्त करें",
        "कार्ड में एनपीके (NPK) स्तर और अनुशंसित उर्वरक दिखाई देंगे",
      ],
      states: "पूरे भारत में",
      website: "https://soilhealth.dac.gov.in",
      color: "soil",
    },
    {
      id: "enam",
      name: "राष्ट्रीय कृषि बाजार (e-NAM)",
      shortName: "e-NAM",
      category: "Market",
      benefit: "मंडियों में बेहतर कीमतों पर सीधे फसल बेचने के लिए ऑनलाइन ट्रेडिंग प्लेटफॉर्म",
      amount: "किसानों के लिए 0% कमीशन (खरीदार 0.3% का भुगतान करते हैं)",
      eligibility: ["अपने स्थानीय एपीएमसी (APMC) मंडी में पंजीकृत कोई भी किसान", "फसलें अधिसूचित वस्तुओं की सूची में होनी चाहिए"],
      documents: ["आधार कार्ड", "बैंक खाता विवरण", "APMC मंडी पंजीकरण प्रमाण पत्र"],
      howToApply: [
        "enam.gov.in पर पंजीकरण करें या अपने स्थानीय मंडी में जाएं",
        "आधार और बैंक विवरण जमा करें",
        "e-NAM आईडी और पासवर्ड प्राप्त करें",
        "मात्रा और ग्रेड के साथ अपनी उपज सूचीबद्ध करें",
        "भारत भर के खरीदार बोली लगा सकते हैं — सर्वोत्तम मूल्य स्वीकार करें",
      ],
      states: "22 राज्य, 1000+ मंडियां शामिल",
      website: "https://enam.gov.in",
      color: "terracotta",
    },
    {
      id: "pkvy",
      name: "परम्परागत कृषि विकास योजना",
      shortName: "PKVY",
      category: "Soil & Organic",
      benefit: "जैविक खेती अपनाने और प्रमाणित होने के लिए वित्तीय सहायता",
      amount: "₹50,000 प्रति हेक्टेयर 3 वर्षों में (₹31,000 सीधे किसान को)",
      eligibility: [
        "जैविक खेती में बदलने के इच्छुक किसान",
        "कम से कम 20 किसानों का एक समूह (क्लस्टर) बनाना होगा",
        "कम से कम 20 हेक्टेयर की सघन भूमि होनी चाहिए",
      ],
      documents: ["आधार कार्ड", "भूमि रिकॉर्ड", "समूह/क्लस्टर गठन प्रमाण पत्र"],
      howToApply: [
        "अपने गाँव में 20+ किसानों का एक समूह बनाएं",
        "जिला कृषि अधिकारी से संपर्क करें",
        "भूमि रिकॉर्ड के साथ समूह आवेदन पत्र जमा करें",
        "सरकार द्वारा आयोजित प्रशिक्षण सत्रों में भाग लें",
        "3 वर्षों में प्रमाणन और वित्तीय सहायता प्राप्त करें",
      ],
      states: "पूरे भारत में",
      website: "https://pgsindia-ncof.gov.in",
      color: "primary",
    },
    {
      id: "raftaar",
      name: "राष्ट्रीय कृषि विकास योजना",
      shortName: "RKVY",
      category: "Technology",
      benefit: "कृषि यंत्रीकरण, बुनियादी ढांचे और तकनीक अपनाने के लिए सब्सिडी",
      amount: "कृषि मशीनरी और उपकरणों पर 50-80% तक सब्सिडी",
      eligibility: ["व्यक्तिगत किसान और किसान उत्पादक संगठन (FPO)", "एससी/एसटी किसानों को प्राथमिकता (80% सब्सिडी)", "छोटे और सीमांत किसानों को प्राथमिकता"],
      documents: ["आधार कार्ड", "भूमि रिकॉर्ड", "आय प्रमाण पत्र", "उपकरण के लिए डीलर कोटेशन"],
      howToApply: [
        "जिला कृषि कार्यालय पर जाएं",
        "विशिष्ट मशीनरी सब्सिडी के लिए आवेदन करें",
        "भूमि और आय के दस्तावेज जमा करें",
        "अनुमोदित डीलर से उपकरण खरीदें",
        "सब्सिडी का दावा करने के लिए खरीद चालान जमा करें",
      ],
      states: "पूरे भारत में (राज्य-वार कोटा)",
      website: "https://rkvy.nic.in",
      color: "wheat",
    },
  ],
  mr: [
    {
      id: "pmkisan",
      name: "पीएम किसान सन्मान निधी",
      shortName: "PM-KISAN",
      category: "Income Support",
      benefit: "सर्व जमीनधारक शेतकरी कुटुंबांना थेट आर्थिक मदत",
      amount: "₹६,००० प्रति वर्ष ₹२,००० च्या ३ समान हप्त्यांमध्ये",
      eligibility: [
        "भारतातील सर्व शेतजमीन असलेले शेतकरी कुटुंब",
        "जमीन शेतकरी किंवा त्याच्या कुटुंबातील सदस्याच्या नावावर असावी",
        "संस्थात्मक जमीनधारक या योजनेसाठी पात्र नाहीत",
        "शासकीय कर्मचारी आणि आयकर भरणारे शेतकरी पात्र नाहीत",
      ],
      documents: ["आधार कार्ड", "जमिनीचे उतारे (७/१२ किंवा ८-अ)", "आधारशी जोडलेले बँक खाते", "मोबाईल नंबर"],
      howToApply: [
        "pmkisan.gov.in ला भेट द्या किंवा जवळच्या महा-ई-सेवा / CSC केंद्रावर जा",
        "'New Farmer Registration' वर क्लिक करा",
        "आधार नंबर आणि राज्य निवडा",
        "जमीन आणि बँकेची माहिती भरा",
        "अर्ज सादर करा आणि नोंदणी क्रमांक जतन करा",
      ],
      states: "संपूर्ण भारत",
      website: "https://pmkisan.gov.in",
      color: "leaf",
    },
    {
      id: "pmfby",
      name: "पंतप्रधान फसल विमा योजना",
      shortName: "PMFBY",
      category: "Insurance",
      benefit: "नैसर्गिक आपत्ती, कीड आणि रोगांमुळे होणाऱ्या नुकसानासाठी पीक विमा संरक्षण",
      amount: "प्रीमियम: खरीप पिकांसाठी २%, रब्बीसाठी १.५%, नगदी पिकांसाठी ५%. उर्वरित रक्कम सरकार भरते.",
      eligibility: [
        "अधिसूचित पिके घेणारे सर्व शेतकरी (कर्जदार आणि बिगर कर्जदार)",
        "कुळ कायदा अंतर्गत असणारे आणि हिस्सेदार शेतकरी दोघेही पात्र",
        "अधिकृत ७/१२ किंवा भाडेकरार असणे आवश्यक",
      ],
      documents: ["आधार कार्ड", "७/१२ उतारा / भाडेकरार", "बँक पासबुक", "तलाठ्याकडून घेतलेला पिकाचा पेरणी दाखला", "मोबाईल नंबर"],
      howToApply: [
        "तुमच्या बँकेला, सीएससी (CSC) केंद्राला किंवा विमा कंपनीला भेट द्या",
        "PMFBY अर्ज भरा",
        "पेरणी दाखला आणि जमिनीचे उतारे सादर करा",
        "लागू असणारी प्रीमियम रक्कम भरा",
        "विमा पॉलिसीचे कागदपत्र मिळवा",
      ],
      states: "संपूर्ण भारत",
      website: "https://pmfby.gov.in",
      color: "sky",
    },
    {
      id: "kcc",
      name: "किसान क्रेडिट कार्ड",
      shortName: "KCC",
      category: "Credit",
      benefit: "वार्षिक ४% या सवलतीच्या व्याजदराने शेतीच्या गरजांसाठी अल्पमुदतीचे कर्ज",
      amount: "कर्ज मर्यादा जमीन आणि पिकाच्या आधारे — सहसा ₹१.६० लाख ते ₹३ लाख",
      eligibility: [
        "सर्व शेतकरी — वैयक्तिक, संयुक्त कर्जदार, कूळ शेतकरी, स्वयंसहायता गट (SHG)",
        "जमिनीच्या क्षेत्राची कोणतीही कमाल मर्यादा नाही",
        "सध्याच्या केसीसी धारकांना कर्ज मर्यादा वाढवून मिळू शकते",
      ],
      documents: ["आधार कार्ड", "पॅन कार्ड", "७/१२ आणि ८-अ उतारा", "पासपोर्ट आकाराचा फोटो", "बँक खात्याचा तपशील"],
      howToApply: [
        "जवळच्या बँक शाखेला (कोणतीही सरकारी, खाजगी किंवा सहकारी बँक) भेट द्या",
        "केसीसी (KCC) अर्जाची मागणी करा",
        "जमीन आणि पिकांच्या तपशीलासह अर्ज भरा",
        "बँक अधिकारी जागेची पाहणी करतील आणि कर्ज मर्यादा मंजूर करतील",
        "केसीसी कार्ड मिळवा आणि पिन जनरेट करून सक्रिय करा",
      ],
      states: "संपूर्ण भारत",
      website: "https://www.india.gov.in/spotlight/kisan-credit-card",
      color: "wheat",
    },
    {
      id: "shc",
      name: "मृदा आरोग्य पत्रिका योजना",
      shortName: "SHC",
      category: "Soil & Organic",
      benefit: "दर २ वर्षांनी मोफत माती परीक्षण आणि वैयक्तिक खत शिफारसी",
      amount: "मोफत सेवा — शेतकऱ्यांसाठी कोणताही खर्च नाही",
      eligibility: ["भारतातील सर्व शेतकरी", "अल्पभूधारक आणि मोठे जमीनधारक दोन्ही पात्र"],
      documents: ["आधार कार्ड", "जमिनीचे उतारे (७/१२)", "मोबाईल नंबर"],
      howToApply: [
        "स्थानिक कृषी विभाग किंवा कृषी विज्ञान केंद्राशी (KVK) संपर्क साधा",
        "मातीचा नमुना द्या (तुमच्या शेतातून ६ इंच खोलीवर घेतलेली २०० ग्रॅम माती)",
        "नमुने शासकीय मृदा चाचणी प्रयोगशाळेत तपासले जातील",
        "३० दिवसांच्या आत मृदा आरोग्य पत्रिका (Soil Health Card) मिळवा",
        "पत्रिकेत एनपीके (NPK) ची पातळी आणि शिफारस केलेली खते दाखवली जातील",
      ],
      states: "संपूर्ण भारत",
      website: "https://soilhealth.dac.gov.in",
      color: "soil",
    },
    {
      id: "enam",
      name: "राष्ट्रीय कृषी बाजार (e-NAM)",
      shortName: "e-NAM",
      category: "Market",
      benefit: "बाजार समित्यांमध्ये चांगल्या किमतीत थेट पिके विकण्यासाठी ऑनलाइन ट्रेडिंग प्लॅटफॉर्म",
      amount: "शेतकऱ्यांसाठी ०% कमिशन (खरेदीदार ०.३% भरतात)",
      eligibility: ["जवळच्या कृषी उत्पन्न बाजार समितीत (APMC) नोंदणीकृत असलेला कोणताही शेतकरी", "पिके अधिसूचित वस्तूंच्या यादीत असावीत"],
      documents: ["आधार कार्ड", "बँक खात्याचा तपशील", "APMC बाजार समिती नोंदणी प्रमाणपत्र"],
      howToApply: [
        "enam.gov.in वर नोंदणी करा किंवा तुमच्या बाजार समितीत जा",
        "आधार आणि बँकेचा तपशील सादर करा",
        "e-NAM आयडी आणि पासवर्ड मिळवा",
        "उत्पादनाचा प्रकार, प्रतवारी आणि संख्या टाकून विक्रीसाठी नोंदणी करा",
        "देशभरातील व्यापारी बोली लावतील — सर्वात चांगला भाव स्वीकारून विका",
      ],
      states: "२२ राज्ये, १०००+ बाजार समित्या समाविष्ट",
      website: "https://enam.gov.in",
      color: "terracotta",
    },
    {
      id: "pkvy",
      name: "परंपरागत कृषी विकास योजना",
      shortName: "PKVY",
      category: "Soil & Organic",
      benefit: "सेंद्रिय शेतीचा अवलंब करण्यासाठी आणि प्रमाणपत्र मिळवण्यासाठी आर्थिक मदत",
      amount: "३ वर्षात ₹५०,००० प्रति हेक्टर (₹३१,००० थेट शेतकऱ्याच्या खात्यात)",
      eligibility: [
        "सेंद्रिय शेती करण्यास इच्छुक असणारे शेतकरी",
        "किमान २० शेतकऱ्यांचा एक गट (क्लस्टर) तयार करणे आवश्यक",
        "गटाकडे किमान २० हेक्टर सलग शेतजमीन असावी",
      ],
      documents: ["आधार कार्ड", "७/१२ उतारा", "शेतकरी गट/क्लस्टर स्थापन प्रमाणपत्र"],
      howToApply: [
        "तुमच्या गावात २०+ शेतकऱ्यांचा एक गट तयार करा",
        "तालुका/जिल्हा कृषी अधिकाऱ्यांशी संपर्क साधा",
        "जमिनीच्या उताऱ्यांसह गटाचा अर्ज सादर करा",
        "शासनाकडून आयोजित सेंद्रिय शेती प्रशिक्षण सत्रांना उपस्थित राहा",
        "३ वर्षांच्या कालावधीत सेंद्रिय प्रमाणपत्र आणि आर्थिक मदत मिळवा",
      ],
      states: "संपूर्ण भारत",
      website: "https://pgsindia-ncof.gov.in",
      color: "primary",
    },
    {
      id: "raftaar",
      name: "राष्ट्रीय कृषी विकास योजना",
      shortName: "RKVY",
      category: "Technology",
      benefit: "शेतीचे यांत्रिकीकरण, पायाभूत सुविधा आणि नवीन तंत्रज्ञान वापरण्यासाठी सबसिडी",
      amount: "कृषी यंत्रसामग्री आणि अवजारांवर ५०-८०% सबसिडी",
      eligibility: ["वैयक्तिक शेतकरी आणि शेतकरी उत्पादक कंपन्या (FPO)", "अनुसूचित जाती/जमाती शेतकऱ्यांना प्राधान्य (८०% सबसिडी)", "अल्पभूधारक व सीमांत शेतकऱ्यांना प्राधान्य"],
      documents: ["आधार कार्ड", "७/१२ आणि ८-अ उतारा", "उत्पन्नाचा दाखला", "अवजाराचे अधिकृत कोटेशन"],
      howToApply: [
        "जिल्हा/तालुका कृषी कार्यालयाला भेट द्या",
        "विशिष्ट कृषी अवजार सबसिडीसाठी अर्ज करा",
        "जमीन आणि उत्पन्नाची कागदपत्रे सादर करा",
        "मान्यताप्राप्त डीलरकडून अवजार खरेदी करा",
        "खरेदीचे बिल सादर करून सबसिडी थेट खात्यात मिळवा",
      ],
      states: "संपूर्ण भारत (राज्यनिहाय कोटा)",
      website: "https://rkvy.nic.in",
      color: "wheat",
    },
  ],
};
