/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as ProfitRouteImport } from './routes/profit'
import { Route as PlantingGuideRouteImport } from './routes/planting-guide'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MarketRouteImport } from './routes/market'
import { Route as LifecycleRouteImport } from './routes/lifecycle'
import { Route as DiseaseDetectionRouteImport } from './routes/disease-detection'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CropRecommendationRouteImport } from './routes/crop-recommendation'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitRoute = ProfitRouteImport.update({
  id: '/profit',
  path: '/profit',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantingGuideRoute = PlantingGuideRouteImport.update({
  id: '/planting-guide',
  path: '/planting-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const LifecycleRoute = LifecycleRouteImport.update({
  id: '/lifecycle',
  path: '/lifecycle',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseaseDetectionRoute = DiseaseDetectionRouteImport.update({
  id: '/disease-detection',
  path: '/disease-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CropRecommendationRoute = CropRecommendationRouteImport.update({
  id: '/crop-recommendation',
  path: '/crop-recommendation',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRouteWithChildren
  '/community': typeof CommunityRoute
  '/crop-recommendation': typeof CropRecommendationRoute
  '/dashboard': typeof DashboardRoute
  '/disease-detection': typeof DiseaseDetectionRoute
  '/lifecycle': typeof LifecycleRoute
  '/market': typeof MarketRoute
  '/notifications': typeof NotificationsRoute
  '/planting-guide': typeof PlantingGuideRoute
  '/profit': typeof ProfitRoute
  '/schemes': typeof SchemesRoute
  '/settings': typeof SettingsRoute
  '/weather': typeof WeatherRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRouteWithChildren
  '/community': typeof CommunityRoute
  '/crop-recommendation': typeof CropRecommendationRoute
  '/dashboard': typeof DashboardRoute
  '/disease-detection': typeof DiseaseDetectionRoute
  '/lifecycle': typeof LifecycleRoute
  '/market': typeof MarketRoute
  '/notifications': typeof NotificationsRoute
  '/planting-guide': typeof PlantingGuideRoute
  '/profit': typeof ProfitRoute
  '/schemes': typeof SchemesRoute
  '/settings': typeof SettingsRoute
  '/weather': typeof WeatherRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRouteWithChildren
  '/community': typeof CommunityRoute
  '/crop-recommendation': typeof CropRecommendationRoute
  '/dashboard': typeof DashboardRoute
  '/disease-detection': typeof DiseaseDetectionRoute
  '/lifecycle': typeof LifecycleRoute
  '/market': typeof MarketRoute
  '/notifications': typeof NotificationsRoute
  '/planting-guide': typeof PlantingGuideRoute
  '/profit': typeof ProfitRoute
  '/schemes': typeof SchemesRoute
  '/settings': typeof SettingsRoute
  '/weather': typeof WeatherRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/chat'
    | '/community'
    | '/crop-recommendation'
    | '/dashboard'
    | '/disease-detection'
    | '/lifecycle'
    | '/market'
    | '/notifications'
    | '/planting-guide'
    | '/profit'
    | '/schemes'
    | '/settings'
    | '/weather'
    | '/chat/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/chat'
    | '/community'
    | '/crop-recommendation'
    | '/dashboard'
    | '/disease-detection'
    | '/lifecycle'
    | '/market'
    | '/notifications'
    | '/planting-guide'
    | '/profit'
    | '/schemes'
    | '/settings'
    | '/weather'
    | '/chat/$threadId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calendar'
    | '/chat'
    | '/community'
    | '/crop-recommendation'
    | '/dashboard'
    | '/disease-detection'
    | '/lifecycle'
    | '/market'
    | '/notifications'
    | '/planting-guide'
    | '/profit'
    | '/schemes'
    | '/settings'
    | '/weather'
    | '/chat/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  ChatRoute: typeof ChatRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  CropRecommendationRoute: typeof CropRecommendationRoute
  DashboardRoute: typeof DashboardRoute
  DiseaseDetectionRoute: typeof DiseaseDetectionRoute
  LifecycleRoute: typeof LifecycleRoute
  MarketRoute: typeof MarketRoute
  NotificationsRoute: typeof NotificationsRoute
  PlantingGuideRoute: typeof PlantingGuideRoute
  ProfitRoute: typeof ProfitRoute
  SchemesRoute: typeof SchemesRoute
  SettingsRoute: typeof SettingsRoute
  WeatherRoute: typeof WeatherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profit': {
      id: '/profit'
      path: '/profit'
      fullPath: '/profit'
      preLoaderRoute: typeof ProfitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planting-guide': {
      id: '/planting-guide'
      path: '/planting-guide'
      fullPath: '/planting-guide'
      preLoaderRoute: typeof PlantingGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifecycle': {
      id: '/lifecycle'
      path: '/lifecycle'
      fullPath: '/lifecycle'
      preLoaderRoute: typeof LifecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disease-detection': {
      id: '/disease-detection'
      path: '/disease-detection'
      fullPath: '/disease-detection'
      preLoaderRoute: typeof DiseaseDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-recommendation': {
      id: '/crop-recommendation'
      path: '/crop-recommendation'
      fullPath: '/crop-recommendation'
      preLoaderRoute: typeof CropRecommendationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  ChatRoute: ChatRouteWithChildren,
  CommunityRoute: CommunityRoute,
  CropRecommendationRoute: CropRecommendationRoute,
  DashboardRoute: DashboardRoute,
  DiseaseDetectionRoute: DiseaseDetectionRoute,
  LifecycleRoute: LifecycleRoute,
  MarketRoute: MarketRoute,
  NotificationsRoute: NotificationsRoute,
  PlantingGuideRoute: PlantingGuideRoute,
  ProfitRoute: ProfitRoute,
  SchemesRoute: SchemesRoute,
  SettingsRoute: SettingsRoute,
  WeatherRoute: WeatherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
